[package]
name = "tunnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "0.10.1", features = ["aes"] }
hkdf = "0.12.3"
rand = "0.8.5"
sha2 = "0.10.6"
